"""Add volume field to Set model

Revision ID: 7c81766a3901
Revises: 
Create Date: 2025-04-02 20:37:03.715842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7c81766a3901'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    op.drop_table('measurements')
    op.drop_table('routines')
    op.drop_table('public_routines')
    op.drop_table('workout_sets')
    op.drop_table('sessions')
    op.drop_table('bodyweight_logs')
    op.drop_table('notifications')
    op.drop_table('saved_items')
    op.drop_table('workout_exercises')
    op.drop_table('workouts')
    op.drop_table('goals')
    op.drop_table('users')
    op.drop_table('routine_likes')
    op.drop_table('statistics')
    op.drop_table('sets')
    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.drop_column('volume')

    op.create_table('sets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('set_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('additional_weight', sa.FLOAT(), nullable=True),
    sa.Column('assistance_weight', sa.FLOAT(), nullable=True),
    sa.Column('time', sa.INTEGER(), nullable=True),
    sa.Column('distance', sa.FLOAT(), nullable=True),
    sa.Column('within_range', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('week_start_date', sa.DATE(), nullable=True),
    sa.Column('exp_gained', sa.INTEGER(), nullable=True),
    sa.Column('workouts_completed', sa.INTEGER(), nullable=True),
    sa.Column('total_volume', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routine_likes',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('routine_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['public_routines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'routine_id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=100), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('streak', sa.INTEGER(), nullable=True),
    sa.Column('exp', sa.INTEGER(), nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(length=200), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('birthday', sa.DATETIME(), nullable=True),
    sa.Column('preferred_weight_unit', sa.VARCHAR(length=10), nullable=True),
    sa.Column('preferred_distance_unit', sa.VARCHAR(length=10), nullable=True),
    sa.Column('preferred_measurement_unit', sa.VARCHAR(length=10), nullable=True),
    sa.Column('privacy_setting', sa.VARCHAR(length=20), nullable=True),
    sa.Column('range_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('recommend_enabled', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('goals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('goal_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('target_value', sa.FLOAT(), nullable=True),
    sa.Column('current_value', sa.FLOAT(), nullable=True),
    sa.Column('is_complete', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.Column('routine_id', sa.INTEGER(), nullable=True),
    sa.Column('exp_gained', sa.INTEGER(), nullable=True),
    sa.Column('volume', sa.FLOAT(), nullable=True),
    sa.Column('total_reps', sa.INTEGER(), nullable=True),
    sa.Column('sets_completed', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('folder_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('date_saved', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('date_sent', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bodyweight_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('session_date', sa.DATETIME(), nullable=True),
    sa.Column('duration', sa.VARCHAR(length=50), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('exercises', sa.TEXT(), nullable=True),
    sa.Column('exp_gained', sa.INTEGER(), nullable=True),
    sa.Column('session_rating', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=200), nullable=True),
    sa.Column('sets_completed', sa.INTEGER(), nullable=True),
    sa.Column('total_reps', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workout_exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('set_number', sa.INTEGER(), nullable=True),
    sa.Column('rest_duration', sa.INTEGER(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('completion_time', sa.DATETIME(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('distance', sa.FLOAT(), nullable=True),
    sa.Column('additional_weight', sa.FLOAT(), nullable=True),
    sa.Column('assistance_weight', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('public_routines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original_routine_id', sa.INTEGER(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('exercises', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.Column('copies', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_routine_id'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('goal', sa.VARCHAR(length=20), nullable=True),
    sa.Column('muscle_groups', sa.VARCHAR(length=200), nullable=True),
    sa.Column('exercises', sqlite.JSON(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('equipment', sa.VARCHAR(length=100), nullable=True),
    sa.Column('muscles_worked', sa.VARCHAR(length=200), nullable=True),
    sa.Column('exercise_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('input_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('user_created', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=200), nullable=True),
    sa.Column('min_reps', sa.INTEGER(), nullable=True),
    sa.Column('max_reps', sa.INTEGER(), nullable=True),
    sa.Column('min_duration', sa.INTEGER(), nullable=True),
    sa.Column('max_duration', sa.INTEGER(), nullable=True),
    sa.Column('min_distance', sa.FLOAT(), nullable=True),
    sa.Column('max_distance', sa.FLOAT(), nullable=True),
    sa.Column('range_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('rest_duration', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ### 