"""Remove goals table

Revision ID: 923642275bdd
Revises: f0bf41ab9d45
Create Date: 2025-04-24 19:19:29.859303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923642275bdd'
down_revision = 'f0bf41ab9d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('goal_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('target_value', sa.FLOAT(), nullable=True),
    sa.Column('current_value', sa.FLOAT(), nullable=True),
    sa.Column('is_complete', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ### 